name: untitled
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  connectivity_plus: ^3.0.2
  bloc_test: ^9.0.3
  equatable: ^2.0.3
  email_validator: ^2.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.15
  intl: any
  crypto: ^3.0.2
  cached_network_image: ^3.2.1
  web_socket_channel: ^2.2.0
  json_annotation: ^4.6.0
  json_serializable: ^6.7.1
  google_fonts: ^4.0.4
  test: ^1.21.1
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.1.1
  oktoast: ^3.3.0
  font_awesome_flutter: ^10.2.1
  badges: ^3.0.2
  go_router: ^10.1.2
  syncfusion_flutter_charts: ^20.2.50
  flutter_switch: ^0.3.2
  package_info_plus: ^3.0.1
  store_redirect: ^2.0.1
  simple_html_css: ^4.0.0
  flutter_html: ^3.0.0-alpha.6
  html_unescape: ^2.0.0
  flutter_typeahead: ^4.1.1
  dotted_border: ^2.0.0+2
  scroll_to_index: ^3.0.1
  file_picker: ^5.2.2
  path_provider: ^2.0.11
  open_file_plus: ^3.3.0
  url_launcher: ^6.1.7
  image_picker: ^0.8.6
  flutter_svg: ^2.0.3
  photo_view: ^0.14.0
  flutter_launcher_icons: ^0.12.0
  carousel_slider: ^4.2.1
  flutter_widget_from_html_core: ^0.10.0
  async: ^2.9.0
  camera: ^0.10.5
  flutter_native_image: ^0.0.6+1
  permission_handler: ^10.2.0
  photo_manager: ^2.6.0
  transparent_image: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  rxdart: ^0.27.7
  image_cropper: ^4.0.1
  diacritic: ^0.1.4
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  flutter_otp_text_field: ^1.1.0+2
  collection: ^1.17.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/background/
    - assets/logo/
    - assets/emoji/
    - assets/icon/
    - assets/image/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
